In [1]:
import torch
import pandas as pd
import numpy as np

### MATHEMATICAL OPERATIONS ON TENSORS

- Tensors Addition
- Tensors subtraction
- Tensors Multiplication (element wise)
- Tensors Divison
- Tensors Multiplication(matrix multiplication)

#### USING OPERATORS

In [ ]:
### CREATING A TENSOR
TENSOR_A=torch.tensor([[[1,2,3],[1,2,3],[1,2,3]]])
TENSOR_A,TENSOR_A.ndim,TENSOR_A.shape

(tensor([[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
## addition with a scalar
TENSOR_A+100

tensor([[[101, 102, 103],
         [101, 102, 103],
         [101, 102, 103]]])

In [ ]:
###subtraction with scalar
TENSOR_A-1

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]])

In [ ]:
###multiplocation with scalar
TENSOR_A*10

tensor([[[10, 20, 30],
         [10, 20, 30],
         [10, 20, 30]]])

In [ ]:
##divison with scalar
TENSOR_A/10

tensor([[[0.1000, 0.2000, 0.3000],
         [0.1000, 0.2000, 0.3000],
         [0.1000, 0.2000, 0.3000]]])

#### using PyTorch inbuilt functions

In [ ]:
##addition
torch.add(TENSOR_A,100)

tensor([[[101, 102, 103],
         [101, 102, 103],
         [101, 102, 103]]])

In [ ]:
##subtraction
torch.sub(TENSOR_A,1)

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]])

In [ ]:
#multiplocation
torch.mul(TENSOR_A,10)

tensor([[[10, 20, 30],
         [10, 20, 30],
         [10, 20, 30]]])

In [ ]:
#divison
torch.div(TENSOR_A,10)

tensor([[[0.1000, 0.2000, 0.3000],
         [0.1000, 0.2000, 0.3000],
         [0.1000, 0.2000, 0.3000]]])

### MATRIX MULTIPLICATION
- Matrix multiplication elementwise
- Matrix multiplication (dot product)(@ symbol is for matrix multiplication)

We need to understand the how the tensors are multiplied because dot product is the heart of machine learning and deep learning  

- tirch.mm() is also used for matrix multiplication

In [ ]:
TENSOR_A

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [ ]:
## creating another Tensor
TENSOR_B=torch.tensor([[[4,5,6],[4,5,6,],[4,5,6]]])
TENSOR_B,TENSOR_B.ndim,TENSOR_B.shape

(tensor([[[4, 5, 6],
          [4, 5, 6],
          [4, 5, 6]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
###multiplying tensor a with b elemtwise
torch.mul(TENSOR_A,TENSOR_B)

tensor([[[ 4, 10, 18],
         [ 4, 10, 18],
         [ 4, 10, 18]]])

In [ ]:
##dot product
torch.matmul(TENSOR_A,TENSOR_B)

tensor([[[24, 30, 36],
         [24, 30, 36],
         [24, 30, 36]]])

In [ ]:
## @ symbol is used for matrix multiplication
TENSOR_A @ TENSOR_B

tensor([[[24, 30, 36],
         [24, 30, 36],
         [24, 30, 36]]])

In [ ]:
vect_tensor=torch.tensor([1,2,3])
vect_tensor

tensor([1, 2, 3])

In [ ]:
%%time
torch.matmul(vect_tensor,vect_tensor)

CPU times: user 111 µs, sys: 6 µs, total: 117 µs
Wall time: 123 µs


tensor(14)

In [ ]:
%%time
##using for loop
value=0
for i in range(len(vect_tensor)):
  value+=vect_tensor[i]*vect_tensor[i]
value

CPU times: user 328 µs, sys: 0 ns, total: 328 µs
Wall time: 335 µs


tensor(14)

### RULES OF MATRIX MULTIPLICATION

There are basically two rules of matrix multiplocation
- Inner dimension should match
- The resultant matrix will have the shape of outer dimension

In [ ]:
## multiplication of (3,2) shape tensor with (2,3)
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5205, 0.6852, 0.6047],
        [0.3868, 0.7980, 0.5668],
        [0.3144, 0.4685, 0.3875]])

In [ ]:
## multiplication of (3,2) shape tensor with (4,3)
torch.matmul(torch.rand(3,2),torch.rand(4,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 4x3)

In [ ]:
## multiplication of (5,4) shape tensor with (4,8)
torch.matmul(torch.rand(5,4),torch.rand(4,8))

tensor([[1.3228, 1.6704, 1.6468, 2.4405, 1.7488, 1.3549, 1.4537, 0.9437],
        [0.9367, 1.2734, 1.0348, 1.7278, 1.1480, 1.0103, 1.0333, 0.8362],
        [1.1553, 1.2892, 1.1307, 1.8686, 1.2890, 1.1400, 1.3193, 0.8411],
        [1.2165, 1.6498, 1.7874, 2.4787, 1.8227, 1.2874, 1.2382, 0.8166],
        [1.1233, 1.3848, 1.1106, 1.9496, 1.2786, 1.1895, 1.1845, 0.9404]])

### MOST COMMON OCCURENCES OF ERROR IN DEEP LEARNING : SHAPE ERRROR  

- suppose we have two matrices  matrix_a having shape (3,2) and matrix_b having shape(3,2)
- we can transpose matrix b and then apply matrix multiplication

In [ ]:
##creating tensorA of size 3,2
TENSOR_A=torch.rand(3,2)
TENSOR_A,TENSOR_A.ndim,TENSOR_A.shape

(tensor([[0.4278, 0.6497],
         [0.0233, 0.6146],
         [0.0586, 0.1511]]),
 2,
 torch.Size([3, 2]))

In [ ]:
#creating tensorB of size 2,3
TENSOR_B=torch.rand(3,2)
TENSOR_B,TENSOR_B.ndim,TENSOR_B.shape

(tensor([[0.5333, 0.3183],
         [0.7754, 0.1287],
         [0.4684, 0.5487]]),
 2,
 torch.Size([3, 2]))

In [ ]:
##multiplying
torch.matmul(TENSOR_A,TENSOR_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
## taking transpose of TENSOR B and multiplying----transpose is denoted by Tensor.T
torch.matmul(TENSOR_A,TENSOR_B.T)

tensor([[0.4350, 0.4153, 0.5569],
        [0.2080, 0.0971, 0.3481],
        [0.0794, 0.0649, 0.1104]])

### APPLYING AGGREGATE FUNCTION ON TENSORS
- MIN
- MAX
- SUM
- MEAN (mean functions requires float input datatype)

In [3]:
int_tensor=torch.tensor([1,2,3,4,5])
int_tensor,int_tensor.dtype

(tensor([1, 2, 3, 4, 5]), torch.int64)

In [4]:
### applying min,max,sum ----- first way
torch.min(int_tensor),torch.max(int_tensor),torch.sum(int_tensor)

(tensor(1), tensor(5), tensor(15))

In [5]:
#applying min,max,sum
int_tensor.min(),int_tensor.max(),int_tensor.sum()

(tensor(1), tensor(5), tensor(15))

In [6]:
#applying mean
torch.mean(int_tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
##converting int tensor to float and then applying mean
torch.mean(int_tensor.type(torch.float32)) ,int_tensor.type(torch.float32).mean()

(tensor(3.), tensor(3.))

### FINDING THE POSITIONAL MIN AND MAX
- argmin (finds the index where the minimum value occurs in a tensor )
- argmax (finds the index where the maximum value occurs in a tensor )

In [11]:
tensor_xyz=torch.tensor([34,56,23,78,12,54,39])
tensor_xyz

tensor([34, 56, 23, 78, 12, 54, 39])

In [12]:
#finding argmin
tensor_xyz.argmin()

tensor(4)

In [13]:
#checking the minimum value
tensor_xyz[tensor_xyz.argmin()]

tensor(12)

In [14]:
#finding argmax
tensor_xyz.argmax()

tensor(3)

In [15]:
#checking maximum value
tensor_xyz[tensor_xyz.argmax()]

tensor(78)

### RESHAPING,STACKING,SQUEEZING AND UNSQUEEZING A TENSOR

- RESHAPE--reshape an input tensor to a given shape
- VIEW--returns the view of an input tensor in the given shape but retains same memory as the input tensor.  
- STACKING--combines multiple tensors on top of each other (vstack) or adjacent to each other(hstack)
- SQUEEZING--removes all 1 dimensions from a given tensor .
- UNSQUEEZING--adds 1 dimensions to a given tensor.
- PERMUTE-- returns view of the given tensor with dimensions permuted or swapped.

#### RESHAPING

In [17]:
#creating a tensor
tensor_xyz=torch.arange(1,13)
tensor_xyz,tensor_xyz.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [18]:
##reshaping the tensor----for reshaping the previous and new shape should be compatible
tensor_xyz.reshape(2,6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [19]:
tensor_xyz.reshape(2,8)#---this is not compatible

RuntimeError: shape '[2, 8]' is invalid for input of size 12

In [21]:
tensor_xyz.reshape(4,3)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [22]:
tensor_xyz.reshape(12,1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])

In [23]:
tensor_xyz.reshape(1,12)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

#### VIEW

In [25]:
#view
view_tensor=tensor_xyz.view(3,4)
view_tensor#this view tensor is just a different view of tensor_xyz if we change anything in tensor_xyz it is reflected in view

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [29]:
tensor_xyz

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
tensor_xyz[2:3]

tensor([3])

In [33]:
tensor_xyz[2:3]=100
tensor_xyz,view_tensor

(tensor([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12]),
 tensor([[  1,   2, 100,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]]))

####  STACKING

In [34]:
### stacking a tensor
torch.stack([tensor_xyz,tensor_xyz])

tensor([[  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12],
        [  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12]])

In [37]:
#vertically stacking------with torch.stack and dim=0
torch.stack([tensor_xyz,tensor_xyz],dim=0)

tensor([[  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12],
        [  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12]])

In [38]:
#vertically stacking------with torch.vstack
torch.vstack([tensor_xyz,tensor_xyz])

tensor([[  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12],
        [  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12]])

In [39]:
#horizontally stacking ---with torch.stack and dim=1
torch.stack([tensor_xyz,tensor_xyz],dim=1)

tensor([[  1,   1],
        [  2,   2],
        [100, 100],
        [  4,   4],
        [  5,   5],
        [  6,   6],
        [  7,   7],
        [  8,   8],
        [  9,   9],
        [ 10,  10],
        [ 11,  11],
        [ 12,  12]])

In [41]:
#horizontally stacking ---with torch.hstack
torch.hstack([tensor_xyz,tensor_xyz])

tensor([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,   1,   2,
        100,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [45]:
new_tensor=torch.tensor([[1,2,3,4],[6,7,8,9]])
new_tensor

tensor([[1, 2, 3, 4],
        [6, 7, 8, 9]])

In [46]:
torch.hstack([new_tensor,new_tensor])

tensor([[1, 2, 3, 4, 1, 2, 3, 4],
        [6, 7, 8, 9, 6, 7, 8, 9]])

#### SQUEEZING

In [49]:
### squeezing the tensor ----------#torch.squeeze()
tensor_xyz

tensor([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [48]:
torch.squeeze(tensor_xyz)

tensor([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [52]:
tensor_xyz.reshape(1,3,4)

tensor([[[  1,   2, 100,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]]])

In [53]:
torch.squeeze(tensor_xyz.reshape(1,3,4)) #---here we can see that one dimension is removed

tensor([[  1,   2, 100,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [54]:
tensor_xyz.reshape(1,2,1,6)

tensor([[[[  1,   2, 100,   4,   5,   6]],

         [[  7,   8,   9,  10,  11,  12]]]])

In [55]:
torch.squeeze(tensor_xyz.reshape(1,2,1,6)) ## we can see that all the single dimensions are removed

tensor([[  1,   2, 100,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12]])

#### UNSQUEEZING

In [59]:
#torch.unsqueeze()#it adds a single dimension in the given axis
tensor_xyz.shape,torch.unsqueeze(tensor_xyz,dim=0),torch.unsqueeze(tensor_xyz,dim=0) .shape

(torch.Size([12]),
 tensor([[  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12]]),
 torch.Size([1, 12]))

In [65]:
#torch.unsqueeze()#it adds a single dimension in the given dim=1
tensor_xyz.shape,torch.unsqueeze(tensor_xyz,dim=1),torch.unsqueeze(tensor_xyz,dim=1) .shape

(torch.Size([12]),
 tensor([[  1],
         [  2],
         [100],
         [  4],
         [  5],
         [  6],
         [  7],
         [  8],
         [  9],
         [ 10],
         [ 11],
         [ 12]]),
 torch.Size([12, 1]))

In [60]:
tensor_xyz.reshape(1,2,1,6)

tensor([[[[  1,   2, 100,   4,   5,   6]],

         [[  7,   8,   9,  10,  11,  12]]]])

In [61]:
#creating the squeezed tensor
sqz_tensor=torch.squeeze(tensor_xyz.reshape(1,2,1,6))
sqz_tensor

tensor([[  1,   2, 100,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12]])

In [66]:
#unsqueezing the tensor in dim=0
torch.unsqueeze(sqz_tensor,dim=0),torch.unsqueeze(sqz_tensor,dim=0).shape  ##it added a single dimension in axis dim=0

(tensor([[[  1,   2, 100,   4,   5,   6],
          [  7,   8,   9,  10,  11,  12]]]),
 torch.Size([1, 2, 6]))

In [67]:
#unsqueezing the tensor in dim=1
torch.unsqueeze(sqz_tensor,dim=1),torch.unsqueeze(sqz_tensor,dim=1).shape #it added one dimension in the axes dim=1

(tensor([[[  1,   2, 100,   4,   5,   6]],
 
         [[  7,   8,   9,  10,  11,  12]]]),
 torch.Size([2, 1, 6]))

#### PERMUTE

In [68]:
#permute returns the view of the original tensor with the dimensions rerarranged in the given manner

In [69]:
#creating the image like tensor a
original_tensor=torch.rand(220,300,3)#--(height,width,channel)

#permuting the original_tensor
permuted_tensor=torch.permute(original_tensor,(2,0,1))#---(channel,height,width)

print("original tensor shape :",original_tensor.shape)
print('permuted tensor shape :',permuted_tensor.shape)

original tensor shape : torch.Size([220, 300, 3])
permuted tensor shape : torch.Size([3, 220, 300])


In [72]:
#since permuted gives view then any changes on original tensor will be reflected in permuted tensor
original_tensor[0,0,0],permuted_tensor[0,0,0]

(tensor(0.1527), tensor(0.1527))

In [73]:
#changing the value in original and checking with permuted
original_tensor[0,0,0]=12345
original_tensor[0,0,0],permuted_tensor[0,0,0]

(tensor(12345.), tensor(12345.))