In [21]:
import torch
import numpy as np
torch.__version__

'2.1.0+cu121'

### INDEXING


- Indexing in PyTorch is same as indexing in numpy

In [4]:
##creating a tensor
x=torch.arange(1,13).reshape(1,3,4)
x,x.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]),
 torch.Size([1, 3, 4]))

In [10]:
## getting the 0th dimension
x[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [11]:
##getting dimension 1
x[0][0],x[:,0]
#in the second we are selecting all the 0th dimension and 1 dimension
#in first we are selecting 0yh dimension and dimension 1

(tensor([1, 2, 3, 4]), tensor([[1, 2, 3, 4]]))

In [15]:
## getting dimension 2
x[0][0][0],x[:,0,0]

(tensor(1), tensor([1]))

In [17]:
## getting all the elemnts from 3rd row
x[:,2,:],x[0][2]

(tensor([[ 9, 10, 11, 12]]), tensor([ 9, 10, 11, 12]))

In [19]:
### getting all the elements from 2nd column
x[:,:,1]

tensor([[ 2,  6, 10]])

In [20]:
## getting number 7
x[0][1][2],x[:,1,2]

(tensor(7), tensor([7]))

### NUMPY ARRAY AND TENSORS

- Numpy also known as Numerical Python is a computing library  where operations are performed on arrays.
- PyTorch has functionality to interact with it
- Default datatype of Numpy array is float64
- Default datatype of tensor is float32  
- numpy array to tensor `torch.from_numpy(numpy_array)`

In [25]:
## craeting an array and tensor from array
array=np.arange(1.0,10)
tensor_array=torch.from_numpy(array)
array,tensor_array

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [26]:
#checking datatype of array and tensor
array.dtype,tensor_array.dtype

(dtype('float64'), torch.float64)

In [29]:
x=torch.arange(1.0,10.0)#tensor default dytpe is float32
x,x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [30]:
#changing array to see if tensor array changes
array=array+1
array,tensor_array

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [31]:
#changing tensor array to see if array changes
tensor_array=tensor_array+5
tensor_array,array

(tensor([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14.], dtype=torch.float64),
 array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [39]:
#tensor to numpy
new_tensor=torch.arange(1.0,10.0)
new_tensor,new_tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [40]:
new_tensor.numpy()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

### REPRODUCIBILITY (GENERATING RANDOM FROM RANDOM )

- Neural networks learn by > start with random numbers > tensor operations > update numbers to represent the data >update>update until it becomes the best representation of the data .
- To reduce the randomness in neural networks PyTorch comes with the concept of random seed known as manual seed .

In [32]:
### creating two random tensors

tensor_a=torch.rand(3,4)
tensor_b=torch.rand(3,4)

print(tensor_a)
print(tensor_b)
print(tensor_a==tensor_b)

tensor([[0.9381, 0.5464, 0.9986, 0.9301],
        [0.7363, 0.4525, 0.1046, 0.4374],
        [0.4319, 0.3037, 0.8941, 0.4673]])
tensor([[0.3957, 0.9734, 0.4616, 0.1767],
        [0.4953, 0.0589, 0.8562, 0.2684],
        [0.7738, 0.0965, 0.3171, 0.4909]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [34]:
### setting the seed and creating random tensors with fixed seed
random_seed=42

### we have to call manual seed function everytime when we create random tensor
torch.manual_seed(random_seed)
tensor_c=torch.rand(3,4)

### we have to call manual seed function everytime when we create random tensor
torch.manual_seed(random_seed)
tensor_d=torch.rand(3,4)

print(tensor_c)
print(tensor_d)

print(tensor_c==tensor_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### RUNNING TENSORS AND PYTORCH OBJECTS ON GPU

- GPU means faster compuations + NVIDIA hardware + PyTorch working behind the scenes

#### GETTING A GPU
- google colab
- getting your own gpu
- cloud computing (gcp/aws/azure)


- For Pytorch since it is capable of running compute on GPU or CPU it is best to set the device agnostic code:
- "cuda" if available else "cpu"
- https://pytorch.org/docs/stable/notes/cuda.html

In [1]:
### check for gpu access with Pytorch
import torch
import numpy as np
!nvidia-smi

Mon Feb 19 19:02:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
torch.cuda.is_available()

True

In [3]:
#set up device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
## count number of devices
torch.cuda.device_count()

1

### PUTTING MODELS AND TENSORS ON THE GPU

- because gpu is capable of faster computations

In [5]:
#create a tensor (default on cpu)
tensor_a=torch.arange(1,10)

tensor_a,tensor_a.device

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), device(type='cpu'))

In [7]:
##moving tensor to device
tensor_a.to(device)
tensor_a,tensor_a.device

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), device(type='cpu'))

In [8]:
tensor_a=tensor_a.to(device)
tensor_a,tensor_a.device

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0'),
 device(type='cuda', index=0))

### PUTTING TENSORS BACK ON CPU

In [9]:
# since numpy runs on cpu can we convert the tensor on gpu to numpy
tensor_a=tensor_a.numpy()
tensor_a

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
#to fix numpy with gpu isue we first set the tensor to cpu
tensor_a=tensor_a.cpu()
tensor_a=tensor_a.numpy()
tensor_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])