In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
torch.__version__

'2.1.0+cu121'

In [34]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### TENSORS IN PYTORCH

#### HOW TO CREATE A TENSOR
- tensors are created in pytorch using torch.tensor()

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
#checking dimension
scalar.ndim

0

In [ ]:
#get scalar back as python integer
scalar.item()

7

In [ ]:
#vector creation
vector=torch.tensor([1,2,3,4])
print("vector dimension : ",vector.ndim)
print("vector shape :",vector.shape)

vector dimension :  1
vector shape : torch.Size([4])


In [ ]:
vector

tensor([1, 2, 3, 4])

In [ ]:
#Matrix creation
MATRIX=torch.tensor([[4,8],[3,6]])
MATRIX

tensor([[4, 8],
        [3, 6]])

In [ ]:
print(MATRIX.ndim)
print(MATRIX.shape)


2
torch.Size([2, 2])


In [ ]:
MATRIX[0] #CHECKING THE FIRST DIMENSION OF MATRIX

tensor([4, 8])

In [ ]:
MATRIX[1] #CHECKING SECOND DIMENSION OF MATRIX

tensor([3, 6])

In [ ]:
### tensor creation
TENSOR=torch.tensor([[[1,2],[3,5],[7,8]]])
TENSOR

tensor([[[1, 2],
         [3, 5],
         [7, 8]]])

In [ ]:
#CHECKING SHAPE AND NUMBER OF DIMENSIONS OF A TENSOR
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 2])


In [ ]:
#checking first dimension of tensor
TENSOR[0]

tensor([[1, 2],
        [3, 5],
        [7, 8]])

### RANDOM TENSORS

#### WHY RANDOM TENSORS?

- In most of the neural networks weights can be represented as tensors and they are are randomly initialized and later on they are updated according to the data.

- https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#creating a first random tensor of size 4,5
rand_tensor_1=torch.rand(size=(4,5))
rand_tensor_1


tensor([[0.8461, 0.9889, 0.2631, 0.5287, 0.9381],
        [0.7129, 0.4071, 0.2319, 0.0113, 0.8825],
        [0.1365, 0.5093, 0.1986, 0.7589, 0.8631],
        [0.3759, 0.8207, 0.1591, 0.8784, 0.8027]])

In [ ]:
rand_tensor_1.shape,rand_tensor_1.ndim

(torch.Size([4, 5]), 2)

In [ ]:
### creating a tensor like an image array
# since image has three channels in pytorch it is represented as colour,height,width
#this is just represenation and not real image
image_tensor=torch.rand(size=(3,224,224))
image_tensor

tensor([[[0.5284, 0.4815, 0.9509,  ..., 0.3680, 0.7564, 0.8481],
         [0.1896, 0.6525, 0.1713,  ..., 0.2682, 0.7406, 0.6966],
         [0.8376, 0.7194, 0.4699,  ..., 0.6384, 0.3079, 0.4435],
         ...,
         [0.7638, 0.9583, 0.8177,  ..., 0.7507, 0.3510, 0.8878],
         [0.3870, 0.3855, 0.8604,  ..., 0.4913, 0.8828, 0.1487],
         [0.4288, 0.2662, 0.1838,  ..., 0.5379, 0.8484, 0.9930]],

        [[0.2928, 0.2251, 0.8091,  ..., 0.6137, 0.1562, 0.5190],
         [0.4252, 0.3132, 0.7767,  ..., 0.1430, 0.7563, 0.5577],
         [0.9468, 0.7525, 0.3593,  ..., 0.8498, 0.5739, 0.9168],
         ...,
         [0.1006, 0.7611, 0.5111,  ..., 0.7498, 0.7711, 0.8727],
         [0.5773, 0.3831, 0.3417,  ..., 0.3454, 0.6902, 0.4499],
         [0.9830, 0.8301, 0.9577,  ..., 0.1808, 0.3364, 0.3283]],

        [[0.1378, 0.2478, 0.2263,  ..., 0.4553, 0.3329, 0.7095],
         [0.8132, 0.6496, 0.1652,  ..., 0.2238, 0.3291, 0.2906],
         [0.1361, 0.3791, 0.9064,  ..., 0.3908, 0.2529, 0.

#### CREATING TENSORS OF SZEROS AND ONES


In [ ]:
ZERO_TENSOR=torch.zeros(size=(2,3,4))
ZERO_TENSOR

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ONES_TENSOR=torch.ones(size=(2,3,4))
ONES_TENSOR

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

#### CREATING TENSORS WITH RANGE AND TENSORS LIKE
-https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
### creating tensors with range 20 to 30
twenty_thirty=torch.arange(20,31)
twenty_thirty

tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
floating=torch.arange(1,5,0.5)
floating

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In [ ]:
#creating tensors like
#it creates tensors with same shape as given in input withall values as zeros
tensor_like=torch.zeros_like(input=floating)
tensor_like

tensor([0., 0., 0., 0., 0., 0., 0., 0.])

### TENSOR DATATYPES

Tensors datatype are on of the three reasons of getting error with Pytorch and deep learning.
- Tensors not datatype
- Tensors not right shape
- Tensors not on right device  


- If the two tensors are not of same datatype then we may run into an error
- If the two Tensors are not on same device then also we can encounter an error


- https://en.wikipedia.org/wiki/Precision_(computer_science)

In [41]:
float_32_tensor=torch.tensor([[1,2,3],[4,5,6]],
                             dtype=torch.float32,#what dataype is tensor eg torch.float32 or torch.float16
                             device=None,#on which device the tensor is
                             requires_grad=False)# whetherto track the gradient during tensor operations
float_32_tensor,float_32_tensor.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.float32)

In [42]:
#changing to another dtype
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [43]:
#multiplying different dtype tensor
float_16_tensor*float_32_tensor

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [44]:
#creating int16 tensor
int_16_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int16)
int_16_tensor

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)

In [45]:
#multiplying int16 tensor with float32 tensor
int_16_tensor*float_32_tensor

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

### GETTING INFORMATION FROM TENSORS (TENSORS ATTRIBUTES)



- checking tensors dataype : tensor.dtype
- checking tensor shape : tensor.shape
- checking device on which tensor is :tensor.device

In [46]:
random_tensor=torch.rand(size=(2,3,4))
random_tensor

tensor([[[0.1242, 0.1194, 0.5113, 0.6389],
         [0.4140, 0.6871, 0.5604, 0.7618],
         [0.1280, 0.3307, 0.9163, 0.8571]],

        [[0.8831, 0.8119, 0.5738, 0.3273],
         [0.8460, 0.4504, 0.9879, 0.1001],
         [0.4574, 0.4146, 0.3792, 0.3983]]])

In [47]:
print("Dataype of tensor ",random_tensor.dtype)
print("Shape of tensor :",random_tensor.shape)
print("Device :",random_tensor.device)

Dataype of tensor  torch.float32
Shape of tensor : torch.Size([2, 3, 4])
Device : cpu
